name: CI workflow for PUSH event with tags
on:
  push:
    branches: [main]
    tags: ["HCLTech"]
jobs:
  show:
    runs-on: ubuntu-latest
    steps: 
      - run: 
          echo " Hello , hello 123.."
